### ISSUE TITLE
FreeBSD support (binary shared libraries missing)

### ISSUE THREAD

**Issue by hxw** [nginx-clojure/nginx-clojure#104]
I just tried the demo web service on PCBSD  (=FreeBSD 10.2) and it fails with an error:

```
example-projects/clojure-web-example % lein with-profile embed run
Compiling clojure-web-example.handler                    
Compiling clojure-web-example.embed-server
11:24:50.199 [main] INFO  clojure-web-example.embed-server - enable auto-reloading in dev enviroment
2015-11-11 11:24:50[error][77862][main]can not get slib/nginx-clojure-embed-freebsd-x64.so at class path
Exception in thread "main" java.lang.ExceptionInInitializerError, compiling:(/tmp/form-init4480308212592458837.clj:1:73)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
```

Took some tracking down but this seems to indicate the problem:

```
% jar -tvf /usr/home/hsw/.m2/repository/nginx-clojure/nginx-clojure-embed/0.4.3/nginx-clojure-embed-0.4.3.jar |grep slib 
     0 Fri Oct 23 11:29:36 CST 2015 slib/
660832 Fri Oct 23 10:37:50 CST 2015 slib/nginx-clojure-embed-linux-i386.so
979177 Fri Oct 23 10:46:38 CST 2015 slib/nginx-clojure-embed-linux-x64.so
842240 Fri Oct 23 10:31:26 CST 2015 slib/nginx-clojure-embed-windows-x86.dll
648136 Fri Oct 23 11:25:46 CST 2015 slib/nginx-clojure-embed-macosx-x64.dylib
1029120 Fri Oct 23 10:34:50 CST 2015 slib/nginx-clojure-embed-windows-x64.dll
```

There appears to be no FreeBSD version of the shared library.

I wondered if this repo is being automatically built by some service and if it is possible to
add FreeBSD to the build system?

**Comment by xfeep** [comment]
@hxw Neither nginx-clojure nor nginx-clojure-embed 's binary distributions include freebsd pre-build binaries.But you can build it by youself.  e.g. For build nginx-clojure-embed

```shell
$ wget https://github.com/nginx/nginx/archive/release-1.8.0.tar.gz
$ tar xzvf  release-1.8.0.tar.gz
$ export NGX_SRC=`pwd`/nginx-release-1.8.0
$ git clone https://github.com/nginx-clojure/nginx-clojure.git
$ cd nginx-clojure/nginx-clojure-embed
$ ./configure
$ make -j
$ lein jar
$ lein install
```

**Comment by hxw** [comment]
Works great, thanks very much
