### ISSUE TITLE
RHEL7: nginx-clojure fails in the configuration phase of nginx

### ISSUE THREAD

**Issue by kjniemi** [nginx-clojure/nginx-clojure#108]
Works on EL6, bombs out on EL7:

``% java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
``

``
adding module in nginx-clojure/src/c
javac is /bin/javac
java is /bin/java
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at nginx.clojure.DiscoverJvm.main(DiscoverJvm.java:96)
Caused by: java.lang.NullPointerException
        at nginx.clojure.DiscoverJvm.getJniIncludes(DiscoverJvm.java:64)
        ... 5 more
append -ldl for Linux:3.10.0-229.20.1.el7.x86_64:x86_64
 + ngx_http_clojure_module was configured
``

**Comment by kjniemi** [comment]
Nevermind - somehow I was building with OpenJDK instead of Oracle JDK

**Comment by xfeep** [comment]
@kjniemi Thanks for your reporting. This NPE means that it failed to detect JNI header path. But I don't know why this error happens with open-jdk 8 on EL7. Commit 56ef539 uses a more useful error message instead of NPE.

**Comment by kjniemi** [comment]
Thank you, @xfeep. Perhaps it is useful for someone who is using OpenJDK :)
