### ISSUE TITLE
Trying to host JAX RS REST API within nginx clojure server. 

### ISSUE THREAD

**Issue by pula2000** [nginx-clojure/nginx-clojure#130]
Can someone give me rough steps as to how to do that? I already have my jersey api code. I don't know how to connect that to nginx clojure api??

**Comment by xfeep** [comment]
[This link](http://nginx-clojure.github.io/more.html#39--java-standard-restful-web-services-with-jersey) should be useful.

**Comment by pula2000** [comment]
Thanks. So I followed all the steps for setting a jersey api within nginx clojure, but I get this error when I start the nginx server - 
![image](https://cloud.githubusercontent.com/assets/6827157/16973579/69eb1970-4dfa-11e6-974b-8008c3013eb9.png)

**Comment by pula2000** [comment]
But I do have java 8 setup and I've pointed the path of the jvm in the nginx.conf file

**Comment by xfeep** [comment]
It is a bug about JNI of jdk on macosx, please check [this link](http://stackoverflow.com/questions/19563766/eclipse-kepler-for-os-x-mavericks-request-java-se-6/19594116#19594116) to resolve it.

**Comment by pula2000** [comment]
I've moved to linux (cent os). I wanted to know whether nginx clojure accepts war file of my dynamic web project in eclipse or not. Or does it have to be only a jar file??
Coz right now with jar I'm getting an error as it doesn't have its maven dependencies in it.

**Comment by pula2000** [comment]
So the exact issue is -xception in thread "main" java.lang.IllegalArgumentException: Can't create  NginxBridge:nginx.clojure.jersey.NginxJerseyContainer
	at nginx.clojure.bridge.NginxBridgeStarter.start(NginxBridgeStarter.java:90)
	at nginx.clojure.bridge.NginxBridgeHandler.config(NginxBridgeHandler.java:58)
	at nginx.clojure.java.NginxJavaHandler.config(NginxJavaHandler.java:195)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:874)
Caused by: java.lang.NoClassDefFoundError: javax/ws/rs/core/SecurityContext

Now the path where its looking isnt correct this class is located in a different path within .m2/repository
So ne ideas how do I fix it?

**Comment by xfeep** [comment]
Please try
 
```nginx
##we can put jars into some dir then all of their path will be appended into the classpath
content_handler_property bridge.lib.dirs 'my-jersey-libs-dir:myother-dir';
```

All jar files and directories in `bridge.lib.dirs` will be used to load classes . e.g. 

```
my-libs ---- (parent directory)
           /a.jar
           /b.jar
           /classes --- (directory)
```

When my-libs is in `bridge.lib.dirs`   a.jar, b.jar and classes will be used to load classes.

**Comment by pula2000** [comment]
Thanks. I fixed that issue by manually adding all relevant jars. Ne idea why this is happening - 016-07-20 22:26:29[info][3571][main]nginx.clojure.jersey.NginxJerseyContainer.boot() with whole classpath: [file:/usr/local/nginx/jars/nginx-jersey-0.1.3.jar]
Jul 20, 2016 10:26:29 PM org.glassfish.hk2.utilities.reflection.Logger warning
WARNING: Cannot find a default implementation of the HK2 ServiceLocatorGenerator
Exception in thread "main" java.lang.IllegalStateException: No generator was provided and there is no default generator registered
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.internalCreate(ServiceLocatorFactoryImpl.java:261)
	at org.glassfish.hk2.internal.ServiceLocatorFactoryImpl.create(ServiceLocatorFactoryImpl.java:225)
	at org.glassfish.jersey.internal.inject.Injections._createLocator(Injections.java:138)
	at org.glassfish.jersey.internal.inject.Injections.createLocator(Injections.java:123)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:325)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:299)
	at nginx.clojure.jersey.NginxJerseyContainer.boot(NginxJerseyContainer.java:75)
	at nginx.clojure.bridge.NginxBridgeStarter.start(NginxBridgeStarter.java:94)
	at nginx.clojure.bridge.NginxBridgeHandler.config(NginxBridgeHandler.java:58)
	at nginx.clojure.java.NginxJavaHandler.config(NginxJavaHandler.java:195)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:874)

**Comment by xfeep** [comment]
Maybe some jars needed are not in the classpath ,e.g. hk2-locator-*.jar

**Comment by pula2000** [comment]
Yep that was the problem. Anyway I added couple more required jars and successfully got my REST service to run within nginx server. Thank you so much!

**Comment by xfeep** [comment]
Not at all.
