### ISSUE TITLE
Problem when trying wave-configuration dump

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#148]
I'm try do wave-configuration dump.

My nginx.conf look like that:

...
jvm_path auto;
jvm_classpath "/usr/local/sbtwaf/lib/*";
#turn on run tool mode, t means Tool
jvm_options "-javaagent/a:/usr/local/sbtwaf/lib/nginx-clojure-0.4.4.jar=tmb";
#for clojure, you should append clojure core jar, e.g -Djava.class.path=jars/nginx-clojure-0.2.7.jar:mypath-xxx/clojure-1.5.1.jar,please  replace ':' with ';' on windows
    jvm_options "-Xbootclasspath/a:/usr/local/sbtwaf/lib/nginx-clojure-0.4.4.jar";
    jvm_options "-Dnginx.clojure.logger.level=debug";
    jvm_options "-Dnginx.clojure.wave.CfgToolOutFile=/tmp/my-wave-cfg.txt";
    include server.conf;

But I get this error message:

[osboxes@osboxes json_schema_validator]$ curl -v http://localhost:8080/dump
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /dump HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 06 Dec 2016 12:53:00 GMT
< Content-Type: text/plain
< Content-Length: 576
< Connection: keep-alive
< Server: nginx-clojure
< Server: SbtWAF
<
java.lang.NullPointerException
        at nginx.clojure.wave.SuspendMethodTracer.dump(SuspendMethodTracer.java:414)
        at nginx.clojure.wave.SuspendMethodTracer.dump(SuspendMethodTracer.java:404)
        at nginx.clojure.java.WaveConfigurationDumpHandler.invoke(WaveConfigurationDumpHandler.java:19)
        at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:124)
        at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:166)
        at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:97)
        at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1125)
* Connection #0 to host localhost left intact

**Comment by xfeep** [comment]
Could you please show us your error.log

**Comment by dennus** [comment]
```
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config validate rule file: /home/osboxes/controller/sbtwaf/default/validate_json_root_lc.conf
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config validate action: deny
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config responseContentType:application/octet-stream
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config validateErrorResponseCode:403
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config errorMessage:Error in request body
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:config allowEncodingTransform:false
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile trying to read rules file: /home/osboxes/controller/sbtwaf/default/validate_json_root_lc.conf
2016-12-08 11:12:40[debug][8144][main]read  + 6rules lines
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile Normalized rule: location="/service/json", method="post", rulesFile="/home/osboxes/controller/common/js/post_json.json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[0]:location="/service/json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[1]: method="post"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[2]: rulesFile="/home/osboxes/controller/common/js/post_json.json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile process rule  : location =/service/json;request method=post;schema=/home/osboxes/controller/common/js/post_json.json
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile Normalized rule: location="/service/json", method="put", rulesFile="/home/osboxes/controller/common/js/put_json.json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[0]:location="/service/json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[1]: method="put"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile parts[2]: rulesFile="/home/osboxes/controller/common/js/put_json.json"
2016-12-08 11:12:40[debug][8144][main]@JsonValidator:processRulesFile process rule  : location =/service/json;request method=put;schema=/home/osboxes/controller/common/js/put_json.json
2016-12-08 11:13:27[debug][8144][main]#140089548045600: hijack at /service/ws_service_proxy
2016-12-08 11:13:27[debug][8144][main]#140089548045600: hijacked at /service/ws_service_proxy, lns:1
2016-12-08 11:13:27[debug][8144][main]@BodyFilter:invoke: event on open
2016-12-08 11:13:27[debug][8144][main]@BodyFilter:connect:trying get container
2016-12-08 11:13:28[debug][8144][main]@BodyFilter:RemoteClientEndpoint:Connecting to wss://echo.websocket.org:443
2016-12-08 11:13:28[debug][8144][main]@BodyFilter:invoke after creating TrustManager
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:RemoteClientEndpoint:OnOpen connection open
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:RemoteClientEndpoint: connection properties
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:RemoteClientEndpoint: DefaultMaxSessionIdleTimeout=0
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:RemoteClientEndpoint: DefaultAsyncSendTimeout=-1
2016-12-08 11:13:33[info][8144][main]@BodyFilter:invoke: before return
2016-12-08 11:13:33[debug][8144][main]#140089548045600: request /service/ws_service_proxy onTextMessage! size=28, rem=false, first=true, pm=140736545727760, lns=2
2016-12-08 11:13:33[debug][8144][main]onTextMessage fetchStringValidPart : 0, txt=Rock it wi...
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:invoke: event get text
2016-12-08 11:13:33[debug][8144][main]@BodyFilter: check valid false
2016-12-08 11:13:33[debug][8144][main]@soSyncSockerSend socket created
2016-12-08 11:13:33[debug][8144][main]@soSyncSockerSend before read
2016-12-08 11:13:33[debug][8144][main]@BodyFilter: check valid false
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:sendTextMessageToRemoteServer: org.apache.tomcat.websocket.WsSession@2280cdac
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:sendTextMessageToRemoteServer: session max idle timeout 0
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:sendTextMessageToRemoteServer: org.apache.tomcat.websocket.WsRemoteEndpointAsync@1517365b
2016-12-08 11:13:33[debug][8144][main]@BodyFilter:sendTextToRemote: sended message Rock it with HTML5 WebSocket
2016-12-08 11:13:33[debug][8144][main]#140089548045600: request /service/ws_service_proxy onWrite, status=0
2016-12-08 11:13:33[debug][8144][WebSocketClient-SecureIO-2]@BodyFilter:RemoteClientEndpoint:OnMessage message received
2016-12-08 11:13:33[debug][8144][WebSocketClient-SecureIO-2]@BodyFilter:RemoteClientEndpoint:send to init client
2016-12-08 11:13:33[debug][8144][WebSocketClient-SecureIO-2]#140089548045600: send message : 'Rock it wi...', len=42, flush=true, last=false, lns=2
2016-12-08 11:13:33[debug][8144][main]handlePostEvent tag=2, len/data=4040917128
2016-12-08 11:13:42[error][8144][main]server unhandled exception!
java.lang.NullPointerException
        at nginx.clojure.wave.SuspendMethodTracer.dump(SuspendMethodTracer.java:414)
        at nginx.clojure.wave.SuspendMethodTracer.dump(SuspendMethodTracer.java:404)
        at nginx.clojure.java.WaveConfigurationDumpHandler.invoke(WaveConfigurationDumpHandler.java:19)
        at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:124)
        at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:166)
        at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:97)
        at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1125)
2016-12-08 11:13:42[debug][8144][main]#140089286948944: request /dump onClose!
```

**Comment by xfeep** [comment]
Could you please show us the error log at the nginx startup?
The NullPointerException in your case means nginx-clojure did not
initialize some object because of wrong configuration.
BTW the below configuration in your case is wrong :
      jvm_options "-Xbootclasspath/a:/usr/local/
sbtwaf/lib/nginx-clojure-0.4.4";

It should be nginx-clojure runtime jar and clojure jar if clojure handler
is used.

**Comment by dennus** [comment]
Thanks's, this problem was solved, because I has incorrect value in 
jvm_options "-javaagent**/a**:/usr/local/sbtwaf/lib/nginx-clojure-0.4.4.jar=tmb";

But now, I have a new problem. When my handler source contains 
```
rivate ClientEndpointConfig doTrustAllCert() throws NoSuchAlgorithmException, KeyManagementException {
			ClientEndpointConfig clientEndpointConfig;
			TrustManager[] trustAllCerts = new TrustManager[] { new X509TrustManager() {
					public java.security.cert.X509Certificate[] getAcceptedIssuers() {
						return null;
					}

					public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) {
						// No need to implement.
					}

					public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) {
						// No need to implement.
					}
				} };
				if (log.isDebugEnabled())
					log.debug("@WsProxy:invoke after creating TrustManager ");	
				// Install the all-trusting trust manager
				SSLContext sslCtx = SSLContext.getInstance("SSL");
				sslCtx.init(null, trustAllCerts, new java.security.SecureRandom());
				clientEndpointConfig = ClientEndpointConfig.Builder.create().build();
				clientEndpointConfig.getUserProperties().put("org.apache.tomcat.websocket.SSL_CONTEXT", sslCtx);
			return clientEndpointConfig;
		}
```
Wave configuration produce this error:

```
2016-12-09 05:08:16[error][19922][nginx-clojure-worker-0]Unable to transform:null
java.lang.NullPointerException
        at nginx.clojure.wave.MethodDatabase.shouldIgnore(MethodDatabase.java:667)
        at nginx.clojure.wave.JavaAgent$CoroutineConfigurationToolWaver.transform(JavaAgent.java:372)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at sun.misc.Unsafe.defineAnonymousClass(Native Method)
        at java.lang.invoke.InvokerBytecodeGenerator.loadAndInitializeInvokerClass(InvokerBytecodeGenerator.java:284)
        at java.lang.invoke.InvokerBytecodeGenerator.loadMethod(InvokerBytecodeGenerator.java:276)
        at java.lang.invoke.InvokerBytecodeGenerator.generateCustomizedCode(InvokerBytecodeGenerator.java:618)
        at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:654)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:247)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:187)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:176)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:83)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:103)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:108)
        at java.lang.invoke.LambdaForm$NamedFunction.resolve(LambdaForm.java:1078)
        at java.lang.invoke.DirectMethodHandle$Lazy.<clinit>(DirectMethodHandle.java:688)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:231)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:187)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:176)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:83)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1655)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethod(MethodHandles.java:1600)
        at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:779)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCbmhCtor(BoundMethodHandle.java:818)
        at java.lang.invoke.BoundMethodHandle$Factory.makeCtors(BoundMethodHandle.java:763)
        at java.lang.invoke.BoundMethodHandle$SpeciesData.initForBootstrap(BoundMethodHandle.java:361)
        at java.lang.invoke.BoundMethodHandle$SpeciesData.<clinit>(BoundMethodHandle.java:426)
        at java.lang.invoke.BoundMethodHandle.<clinit>(BoundMethodHandle.java:830)
        at java.lang.invoke.LambdaForm.createIdentityForms(LambdaForm.java:1778)
        at java.lang.invoke.LambdaForm.<clinit>(LambdaForm.java:1833)
        at java.lang.invoke.DirectMethodHandle.makePreparedLambdaForm(DirectMethodHandle.java:222)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:187)
        at java.lang.invoke.DirectMethodHandle.preparedLambdaForm(DirectMethodHandle.java:176)
        at java.lang.invoke.DirectMethodHandle.make(DirectMethodHandle.java:83)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:1655)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:1612)
        at java.lang.invoke.MethodHandles$Lookup.getDirectMethodForConstant(MethodHandles.java:1797)
        at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
        at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
        at sun.security.util.AbstractAlgorithmConstraints.loadAlgorithmsMap(AbstractAlgorithmConstraints.java:50)
        at sun.security.util.AbstractAlgorithmConstraints.getAlgorithms(AbstractAlgorithmConstraints.java:78)
        at sun.security.util.DisabledAlgorithmConstraints.<init>(DisabledAlgorithmConstraints.java:77)
        at sun.security.ssl.SSLAlgorithmConstraints.<clinit>(SSLAlgorithmConstraints.java:50)
        at sun.security.ssl.ProtocolVersion.<clinit>(ProtocolVersion.java:114)
        at sun.security.ssl.SSLContextImpl$AbstractSSLContext.<clinit>(SSLContextImpl.java:453)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.security.Provider$Service.getImplClass(Provider.java:1634)
        at java.security.Provider$Service.newInstance(Provider.java:1592)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
        at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
        at org.sbrf.sbtwaf.ws.BodyFilter$RemoteClientEndpoint.connect(BodyFilter.java:165)
        at org.sbrf.sbtwaf.ws.BodyFilter$1.onOpen(BodyFilter.java:353)
        at org.sbrf.sbtwaf.ws.BodyFilter$1.onOpen(BodyFilter.java:344)
```

**Comment by xfeep** [comment]
@dennus 
I think in your case NPE is caused by java8 lambdas which result in null class names. Commit e396f88 fixed it.
BTW nginx-clojure has not been supported SSL in coroutine mode so all SSL connections will keep original behavior viz. blocking way.
