### ISSUE TITLE
NginX with Clojure/Java on Windows 10 - not starting up

### ISSUE THREAD

**Issue by askadian** [nginx-clojure/nginx-clojure#151]
I am facing the issue that Nginx is not starting up. Followed the steps - also mentioned in link --> I downloaded the .zip file containing nginx-clojure-0.4.4, and unzipped it in C:\nginx. My .conf file looks like as below: 
```
daemon  off;

#master_process  off;
#user  nobody;
worker_processes  1;
error_log  logs/error.log;
pid        logs/nginx.pid;
events {
    worker_connections  1024;
}
http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    #jvm_path auto;
    jvm_path 'C:/Program Files/Java/jdk1.8.0_91/jre/bin/server/jvm.dll';
    jvm_var my_other_jars 'C:/nginx-clojure-0.4.4/jars';
    jvm_classpath "#{my_other_jars}/*.jar;libs/*";
    #jvm_options "-Djava.class.path=jars/nginx-clojure-0.4.0.jar;#{my_other_jars}";
    jvm_options "-Xms1024m";
    jvm_options "-Xmx1024m";
    server {
        #listen       8080;
        listen       9091;
        server_name  localhost;
        location / {
            root   html;
            index  index.html index.htm;
        }
    location /java {
        content_handler_type 'java';
        content_handler_name 'mytest.HelloService';
    }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

       location /clojure {
          handler_type 'clojure';
          handler_code ' 
                        (fn[req]
                          {
                            :status 200,
                            :headers {"content-type" "text/plain"},
                            :body  "Hello Clojure & Nginx!" 
                            })
          ';
       }       
    }
}
```
Now I run the nginx-win64.exe as follows:
```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> cd c:\nginx
PS C:\nginx> .\nginx-win64.exe
PS C:\nginx>
```

When I go to localhost:9091, the page does not load meaning nginx is not started.

Here is the snapshot of .log file:
```
java.lang.NoClassDefFoundError: nginx/clojure/MiniConstants
Caused by: java.lang.ClassNotFoundException: nginx.clojure.MiniConstants
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2016/12/26 20:27:48 [error] 8400#4396: can not initialize jvm memory util
2016/12/26 20:27:48 [error] 8400#4396: jvm start times 1
Exception in thread "main" 2016/12/26 20:27:48 [error] 8408#2548: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 2
2016/12/26 20:27:48 [error] 8408#2548: we try quit master now!
2016/12/26 20:27:48 [crit] 8408#2548: ngx_http_clojure_quit_master, file ("C:\nginx\nginx-win64.exe"), arg (""C:\nginx\nginx-win64.exe" -s stop")
2016/12/26 20:27:48 [error] 8584#8808: jvm may be mad for wrong options! See hs_err_pid****.log for detail! restarted 3
2016/12/26 20:27:48 [error] 8584#8808: we try quit master now!
2016/12/26 20:27:48 [crit] 8584#8808: ngx_http_clojure_quit_master, file ("C:\nginx\nginx-win64.exe"), arg (""C:\nginx\nginx-win64.exe" -s stop")
2016/12/26 20:27:48 [error] 2580#8744: CreateFile() "C:\nginx/logs/nginx.pid" failed (2: The system cannot find the file specified)
```

**Comment by knasim** [comment]
that's an easy one !
you probably didn't add the clojure dependency into your pom file  perhaps. 
or if you did - you probably building an incorrect artifact.   perform  a ` jar tvf ` on the jar which should provide you some clues.

**Comment by askadian** [comment]
Hi knasim! Thanks!! 
I downloaded the binaries from this [link](http://nginx-clojure.github.io/installation.html). I don't find any .pom file in the folders. I ran the `jar tvf `command in Windows Powershell - 
```
PS C:\nginx\jars> ls


    Directory: C:\nginx\jars


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/3/2016   5:29 AM         828683 nginx-clojure-0.4.4.jar
-a----         3/4/2016   8:45 AM        1773664 nginx-clojure-embed-0.4.4.jar
-a----       10/25/2015  11:31 AM          12509 nginx-jersey-0.1.3.jar
-a----       10/25/2015  11:31 AM          46740 nginx-tomcat8-0.2.3.jar

PS C:\nginx\jars> C:\'Program Files'\Java\jdk1.8.0_91\bin\jar.exe tvf nginx-clojure-0.4.4.jar > nginx-clojure-0.4.4.txt
PS C:\nginx\jars> C:\'Program Files'\Java\jdk1.8.0_91\bin\jar.exe tvf nginx-clojure-embed-0.4.4.jar > nginx-clojure-embed-0.4.4.txt
PS C:\nginx\jars> C:\'Program Files'\Java\jdk1.8.0_91\bin\jar.exe tvf nginx-jersey-0.1.3.jar > nginx-jersey-0.1.3.txt
PS C:\nginx\jars> C:\'Program Files'\Java\jdk1.8.0_91\bin\jar.exe tvf nginx-tomcat8-0.2.3.jar > nginx-tomcat8-0.2.3.txt
PS C:\nginx\jars> ls


    Directory: C:\nginx\jars


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         3/3/2016   5:29 AM         828683 nginx-clojure-0.4.4.jar
-a----       12/27/2016   5:14 PM          74196 nginx-clojure-0.4.4.txt
-a----         3/4/2016   8:45 AM        1773664 nginx-clojure-embed-0.4.4.jar
-a----       12/27/2016   5:16 PM           4010 nginx-clojure-embed-0.4.4.txt
-a----       10/25/2015  11:31 AM          12509 nginx-jersey-0.1.3.jar
-a----       12/27/2016   5:17 PM           2522 nginx-jersey-0.1.3.txt
-a----       10/25/2015  11:31 AM          46740 nginx-tomcat8-0.2.3.jar
-a----       12/27/2016   5:17 PM           6322 nginx-tomcat8-0.2.3.txt


PS C:\nginx\jars>
```

The ouput files look okay. I have attached for your reference. Thanks!!
[nginx-clojure-0.4.4.txt](https://github.com/nginx-clojure/nginx-clojure/files/674707/nginx-clojure-0.4.4.txt)
[nginx-clojure-embed-0.4.4.txt](https://github.com/nginx-clojure/nginx-clojure/files/674708/nginx-clojure-embed-0.4.4.txt)
[nginx-jersey-0.1.3.txt](https://github.com/nginx-clojure/nginx-clojure/files/674709/nginx-jersey-0.1.3.txt)
[nginx-tomcat8-0.2.3.txt](https://github.com/nginx-clojure/nginx-clojure/files/674710/nginx-tomcat8-0.2.3.txt)

**Comment by askadian** [comment]
Any comments?

**Comment by askadian** [comment]
It is working. All I had to do was to change the classpath in the .conf file as follows:
jvm_classpath "jars/mytest.jar;jars/nginx-clojure-0.4.4.jar;#{my_other_jars}/*.jar;libs/*;";

where, mytest.jar contains the HelloService for java Ring Handler and nginx-clojure-0.4.4.jar contains the miniconstants mentioned above.
Closing the issue!!
