### ISSUE TITLE
IOException while loading wave configuration from class path

### ISSUE THREAD

**Issue by gdurastanti** [nginx-clojure/nginx-clojure#176]
I am attempting to enable Coroutine support in my nginx-clojure instance and have followed the instructions dictated in [this](http://nginx-clojure.github.io/configuration.html#241-enable-coroutine-based-client-socket) guide. However, on start I am receiving an IO exception when it attempts to load my wave configuration file. 

Stack:

`java.io.IOException: can not load resource [wave_cfg.txt] from classpath
        at nginx.clojure.wave.MethodDatabaseUtil.load(MethodDatabaseUtil.java:35)
        at nginx.clojure.wave.JavaAgent.buildClassFileTransformer(JavaAgent.java:191)
        at nginx.clojure.wave.JavaAgent.premain(JavaAgent.java:100)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)`

I have placed my _wave_cfg.txt_ file directly under the coroutine-udfs folder and added it to the class path just as I'm adding my other library paths, and given full permissions to the directories and their subfolders.

Options depicted below...

_jvm_classpath "libs/*:libs/prometric/*:jars/*:coroutine-udfs/*";
jvm_options "-javaagent:/etc/nginx-clojure/jars/nginx-clojure-0.4.5.jar=mb";
jvm_options "-Xbootclasspath/a:/etc/nginx-clojure/jars/nginx-clojure-0.4.5.jar";
jvm_options "-Dnginx.clojure.wave.udfs=wave_cfg.txt";_

Any ideas?

**Comment by xfeep** [comment]
Please show your Dockfile. Issue #157 mybe has some useful notes about running nginx-clojure in a docker container.

**Comment by gdurastanti** [comment]
My Dockerfile is very basic. It works fine without coroutine enabled, just throws the IOException when enabled. 

```
FROM java:8
COPY ./nginx-clojure/ /etc/nginx-clojure/
WORKDIR "/etc/nginx-clojure"
CMD ["./mosaic", "-g", "daemon off;", "-p", "/etc/nginx-clojure"]
```

Note: _mosaic_ is the name I assigned to my nginx binary.

**Comment by xfeep** [comment]
It seems nginx worker process has no permission to access coroutine-udfs/wave_cfg.txt.
Please try add this line to you nginx.conf in docker container.

```shell
## do not use root in non-docker env
user root;
```

Or create a user ,e.g. nginx and grant all permissions about /etc/nginx-clojure to it. e.g.


In nginx.conf

```shell
user nginx;
```

 In docker file

```docker
RUN adduser --system --no-create-home --disabled-login --disabled-password --group nginx
RUN chown -R nginx /etc/nginx-clojure 
```

**Comment by gdurastanti** [comment]
It seems neither option is working. Still receiving the same IOException on start. It doesn't seem to stop the startup operation but on first request I receive:

[warn][18][main]not supported socket options: 128, val: 0 just ignored

All requests fail.

**Comment by gdurastanti** [comment]
So placing the wave_cfg.txt in a subfolder _/coroutine-udfs/sub_ seems to  have resolved that issue. For some reason it would not access it in a top level folder. 

I now am having another issue which I can open another ticket for since its somewhat unrelated but I'll at least mention it here. My requests are throwing unhandled exceptions. Am I using an unsupported library?

```
2017-06-28 18:12:37[error][18][main]unhandled exception in coroutine
java.lang.ClassCastException: org.apache.http.conn.EofSensorInputStream cannot be cast to nginx.clojure.NginxRequest
        at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:108)
        at nginx.clojure.NginxSimpleHandler$CoroutineRunner.run(NginxSimpleHandler.java:292)
        at nginx.clojure.Coroutine.resume(Coroutine.java:246)
        at nginx.clojure.net.NginxClojureSocketImpl.onRead(NginxClojureSocketImpl.java:384)
        at nginx.clojure.net.NginxClojureAsynSocket.onRead(NginxClojureAsynSocket.java:322)
```

**Comment by xfeep** [comment]
Could you please give us a minimal example to reproduce this issue?
