### ISSUE TITLE
Could't create wave configuration file

### ISSUE THREAD

**Issue by dennus** [nginx-clojure/nginx-clojure#185]
Hello! When i'm try to run nginx-clojure in tmb mode, nginx not started and I'm receive the next messages in error log:

017-08-08 09:47:35[info][26680][main]nginx-clojure run on thread pool mode,  coroutineEnabled=false
java.lang.RuntimeException: can not create nginx handler for name : org.sbrf.sbtwaf.validators.JsonSchemaRequestBodyValidatorHandlerNew
	at nginx.clojure.java.NginxJavaHandlerFactory.newInstance(NginxJavaHandlerFactory.java:33)
	at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:46)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:866)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 54
Exception Details:
  Location:
    org/sbrf/sbtwaf/validators/JsonValidationSchemaHandlerNew.<init>()V @54: ldc_w
  Reason:
    Current frame's flags are not assignable to stack map frame's.
  Current Frame:
    bci: @0
    flags: { flagThisUninit }
    locals: { uninitializedThis }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @54
    flags: { }
    locals: { }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 2ab7 0001 1301 1613 0118 b801 1e2a bb00
    0x0000010: 0259 b700 03b5 0004 2abb 0005 59b8 0006
    0x0000020: b200 07b2 0007 b700 08b5 0009 1301 1613
    0x0000030: 0118 b801 21b1 1301 1613 0118 b801 21bf
    0x0000040:                                        
  Exception Handler Table:
    bci [0, 54] => handler: 54
  Stackmap Table:
    full_frame(@54,{},{Object[#291]})

	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at nginx.clojure.java.NginxJavaHandlerFactory.newInstance(NginxJavaHandlerFactory.java:23)
	... 2 more

**Comment by xfeep** [comment]
Is there any java 8 lambda expression in your handler?

**Comment by dennus** [comment]
Yes, my handler has jave 8 lambda expression

**Comment by dennus** [comment]
I'm create simple handler without any lambda expression and now I make conclusion that mistake arise only when specific version of jvm used. For e.g. this problem arives when I'm used jre-1.8.0-openjdk-1.8.0.131-3.b12.el7_3.x86_64, but all work correct on verision jre-1.8.0-openjdk-1.8.0.101-3.b13.el7_2.x86_64,   /lib/jvm/jre-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64/

**Comment by dennus** [comment]
UPD: After change jvm version, wave config dumped. But after running in mb mode, I'm received another errors:

2017-08-14 16:41:38[error][57416][main]Unable to instrument:org/sbrf/sbtwaf/validators/JsonSchemaValidator
java.lang.IndexOutOfBoundsException: Index: 4, Size: 4
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at nginx.clojure.wave.InstrumentConstructorMethod.emitInitHelpMethod(InstrumentConstructorMethod.java:207)
        at nginx.clojure.wave.InstrumentConstructorMethod.trySplitIntoTwoNewMethods(InstrumentConstructorMethod.java:109)
        at nginx.clojure.wave.InstrumentConstructorMethod.accept(InstrumentConstructorMethod.java:308)
        at nginx.clojure.wave.InstrumentClass.visitEnd(InstrumentClass.java:168)
        at nginx.clojure.asm.ClassReader.accept(ClassReader.java:673)
        at nginx.clojure.asm.ClassReader.accept(ClassReader.java:506)
        at nginx.clojure.wave.JavaAgent.instrumentClass(JavaAgent.java:224)
        at nginx.clojure.wave.JavaAgent$CoroutineWaver.transform(JavaAgent.java:261)
        at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
        at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.sbrf.sbtwaf.validators.JsonValidationSchemaHandler.doValidate(JsonValidationSchemaHandler.java:133)
        at org.sbrf.sbtwaf.validators.JsonSchemaRequestBodyValidatorHandler.invoke(JsonSchemaRequestBodyValidatorHandler.java:48)
        at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:125)
        at nginx.clojure.NginxSimpleHandler$CoroutineRunner.run(NginxSimpleHandler.java:292)
        at nginx.clojure.Coroutine.resume(Coroutine.java:246)
        at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:180)
        at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:105)
        at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1133)

**Comment by dennus** [comment]
UPD2: After removing constructor with parameters invocation in handler code (may be problem caused in array list parameter in constructor), I'm received another errors:

java.lang.VerifyError: Illegal type at constant pool entry 20 in class org.sbrf.sbtwaf.validators.ApacheSchemaClient
Exception Details:
  Location:
    org/sbrf/sbtwaf/validators/ApacheSchemaClient.compose(Ljava/util/function/Function;)Ljava/util/function/Function; @2: invokespecial
  Reason:
    Constant pool index 20 is invalid
  Bytecode:
    0x0000000: 2a2b b700 14b0

**Comment by dennus** [comment]
Last problem was solved when I'm remove object constructor with parameters invocation (may be error cause in array list parameter). But after all manipulation I'm received another error:

java.lang.NullPointerException
        at nginx.clojure.net.NginxClojureSocketImpl.connect(NginxClojureSocketImpl.java:219)
        at nginx.clojure.net.NginxClojureSocketImpl.connect(NginxClojureSocketImpl.java:228)
        at nginx.clojure.net.NginxClojureSocketImpl.connect(NginxClojureSocketImpl.java:250)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
        at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)

**Comment by dennus** [comment]
Any comments about this?

**Comment by xfeep** [comment]
@dennus Sorry for too late reply.
Could you please show a minimal example to reproduce it? 
I'm really very busy these days.Thanks!
