### ISSUE TITLE
Not started nginx clojure on Windows

### ISSUE THREAD

**Issue by onderaycicek** [nginx-clojure/nginx-clojure#191]
it gives the following error. what is the problem?

nginx.conf
>jvm_classpath "jars/nginx-clojure-0.4.5.jar";    

error.log
>java.lang.RuntimeException: can not load factory:nginx.clojure.clj.NginxClojureHandlerFactory
	at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:35)
	at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:42)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:866)
Caused by: java.lang.NoClassDefFoundError: clojure/lang/RT
	at nginx.clojure.clj.Constants.<clinit>(Constants.java:27)
	at nginx.clojure.clj.NginxClojureHandlerFactory.<init>(NginxClojureHandlerFactory.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:32)
	... 2 more
Caused by: java.lang.ClassNotFoundException: clojure.lang.RT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more
2017/10/10 12:20:47 [error] 67772#65316: invalid clojure content_handler code :  
						(fn[req]
						  {
						    :status 200,
						    :headers {"content-type" "text/plain"},
						    :body  "Hello Clojure & Nginx!" 
						    })

Shell command result:
>java -cp jars/nginx-clojure-0.4.5.jar nginx.clojure.DiscoverJvm
C:\Program Files\Java\jre-9\bin\server\jvm.dll

**Comment by xfeep** [comment]
It seems you use clojure handler but there's no clojure runtime in the classpath.

**Comment by onderaycicek** [comment]
I have applied the first 3 steps in the quick start direction this error occurs. What is the required path for clojure runtime?

**Comment by xfeep** [comment]
e.g. 
```nginx
jvm_classpath "jars/nginx-clojure-0.4.5.jar;jars/clojure-1.5.1.jar";
```
If you use only java handler clojure runtime is not needed.
