### ISSUE TITLE
Error, when i enable nginx-clojure's Coroutine mode!

### ISSUE THREAD

**Issue by OneHappyStone** [nginx-clojure/nginx-clojure#214]
2018/08/24 18:49:07 [notice] 1112#0: using the "epoll" event method
2018/08/24 18:49:07 [notice] 1112#0: nginx-clojure/0.4.5
2018/08/24 18:49:07 [notice] 1112#0: nginx/1.12.0
2018/08/24 18:49:07 [notice] 1112#0: built by gcc 4.1.2 20080704 (Red Hat 4.1.2-54)
2018/08/24 18:49:07 [notice] 1112#0: OS: Linux 2.6.32-220.23.2.al.ali1.2.alios6.x86_64
2018/08/24 18:49:07 [notice] 1112#0: getrlimit(RLIMIT_NOFILE): 65535:65535
2018/08/24 18:49:07 [notice] 1133#0: start worker processes
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1134
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1135
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1136
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1138
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1140
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1142
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1143
2018/08/24 18:49:07 [notice] 1133#0: start worker process 1144
2018/08/24 18:49:07 [notice] 1134#0: ngx clojure: init pipe for jvm worker, fds: 9, 10
2018/08/24 18:49:07 [notice] 1140#0: ngx clojure: init pipe for jvm worker, fds: 17, 18
2018/08/24 18:49:07 [notice] 1144#0: ngx clojure: init pipe for jvm worker, fds: 23, 24
2018/08/24 18:49:07 [notice] 1135#0: ngx clojure: init pipe for jvm worker, fds: 11, 12
2018/08/24 18:49:07 [notice] 1143#0: ngx clojure: init pipe for jvm worker, fds: 21, 22
2018/08/24 18:49:07 [notice] 1138#0: ngx clojure: init pipe for jvm worker, fds: 15, 16
2018/08/24 18:49:07 [notice] 1136#0: ngx clojure: init pipe for jvm worker, fds: 13, 14
2018/08/24 18:49:07 [notice] 1142#0: ngx clojure: init pipe for jvm worker, fds: 19, 20
2018-08-24 18:49:07[info][1134][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1140][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1144][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1143][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1138][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1135][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1136][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:08[info][1142][main]java agent configured so we turn on coroutine support!
2018-08-24 18:49:23[warn][1144][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:23[warn][1143][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:23[warn][1134][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:23[warn][1138][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:24[warn][1136][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:24[warn][1140][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:24[warn][1142][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:24[warn][1135][pool-2-thread-1]we are not in coroutine so we turn to java build-in socket implement!
2018-08-24 18:49:30[warn][1144][main]not supported socket options: 128, val: 0 just ignored
2018-08-24 18:49:30[error][1144][main]unhandled exception in coroutine
com.happy.exception.RedisDAOException: redis hgetAll exception!
        at com.cc.utils.RedisDAOUtils.hgetAll(RedisDAOUtils.java:106)
        at com.happy.core.RequestHandlerEngine.getZoneCache(RequestHandlerEngine.java:179)
        at com.happy.core.RequestHandlerEngine.executeHandler(RequestHandlerEngine.java:107)
        at com.happy.handler.AbstractNginxJavaRingHandler.invoke(AbstractNginxJavaRingHandler.java:42)
        at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:125)
        at nginx.clojure.NginxSimpleHandler$CoroutineRunner.run(NginxSimpleHandler.java:292)
        at nginx.clojure.Coroutine.resume(Coroutine.java:246)
        at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:180)
        at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:105)
        at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1133)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
        at redis.clients.util.Pool.getResource(Pool.java:53)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:226)
        at com.happy.utils.RedisDAOUtils.hgetAll(RedisDAOUtils.java:103)
        ... 9 more
Caused by: nginx.clojure.SuspendExecution
Exception in thread "main" java.lang.IllegalStateException: Not new or suspended
        at nginx.clojure.Coroutine.resume(Coroutine.java:229)
        at nginx.clojure.net.NginxClojureSocketImpl.onConnect(NginxClojureSocketImpl.java:369)
        at nginx.clojure.net.NginxClojureAsynSocket.onConnect(NginxClojureAsynSocket.java:317)

**my nginx.conf's Coroutine configuration  like this:**

`

    jvm_classpath /alidata/server/nginx-clojure/coroutine-udfs:/alidata/server/nginx-clojure/libs/*;

    jvm_options "-Xms1024m";

    jvm_options "-Xmx1024m";

    jvm_options "-javaagent:jars/nginx-clojure-0.4.5.jar=mb";

    jvm_options "-Xbootclasspath/a:jars/nginx-clojure-0.4.5.jar";

    jvm_options "-Dnginx.clojure.wave.udfs=my-wave-cfg.txt";`

**Comment by xfeep** [comment]
Are all methods which appear in the error stack trace also listed in the generated my-wave-cfg.txt file?

**Comment by OneHappyStone** [comment]
No, the my-wave-cfg.txt file is empty! it shows this message:

############Generated By Nginx-Clojure SuspendMethodTracer 2018-08-24 ##############
#######Notice: Ingored Waving information from current configuration file :[nginx/clojure/wave/coroutine-method-db.txt]

**Comment by xfeep** [comment]
@OneHappyStone 

We tested it with redis java client.

```nginx
    jvm_var ncjar 'jars/nginx-clojure-0.5.1.jar';

    ###run tool mode , 't' means Tool
    jvm_options "-javaagent:#{ncjar}=tmb";
```

```java
	public static class SimpleRedisHandler implements NginxJavaRingHandler {

		/* (non-Javadoc)
		 * @see nginx.clojure.java.NginxJavaRingHandler#invoke(java.util.Map)
		 */
		@Override
		public Object[] invoke(Map<String, Object> request) throws IOException {
			try (Jedis jedis = new Jedis("localhost") ) {
				String value = FileUtils.readFileToString(new File("testfiles/large.txt"), "utf-8");
				jedis.set("myserver", value);
				String body = jedis.get("myserver");
				return new Object[] {Constants.NGX_HTTP_OK, ArrayMap.create("content-type", "text/html"), body};
			}
		}
	}
```

After run commands

```bash
curl http://localhost:8080/redis
curl http://localhost:8080/dump
```

We got the right wave cfg file 

```nginx
############Generated By Nginx-Clojure SuspendMethodTracer 2019-11-27 ##############
#######Notice: Ingored Waving information from current configuration file : [nginx/clojure/wave/coroutine-method-db.txt, compojure-http-clj.txt, mysql-jdbc.txt, test-groovy.txt, https.txt]
fuzzyclass:nginx/clojure/net/RedisCoroutineTestSet(\d+)JavaHandler\$SimpleRedisHandler
  invoke(Ljava/util/Map;)[Ljava/lang/Object;:normal

lazyclass:redis/clients/jedis/BinaryClient
  connect()V:normal
  set([B[B)V:normal

lazyclass:redis/clients/jedis/Client
  set(Ljava/lang/String;Ljava/lang/String;)V:normal

lazyclass:redis/clients/jedis/Connection
  connect()V:normal
  flush()V:normal
  getBinaryBulkReply()[B:normal
  getBulkReply()Ljava/lang/String;:normal
  getStatusCodeReply()Ljava/lang/String;:normal
  readProtocolWithCheckingBroken()Ljava/lang/Object;:normal
  sendCommand(Lredis/clients/jedis/commands/ProtocolCommand;[[B)V:normal

lazyclass:redis/clients/jedis/Jedis
  get(Ljava/lang/String;)Ljava/lang/String;:normal
  set(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;:normal

lazyclass:redis/clients/jedis/Protocol
  process(Lredis/clients/jedis/util/RedisInputStream;)Ljava/lang/Object;:normal
  processBulkReply(Lredis/clients/jedis/util/RedisInputStream;)[B:normal
  read(Lredis/clients/jedis/util/RedisInputStream;)Ljava/lang/Object;:normal
  sendCommand(Lredis/clients/jedis/util/RedisOutputStream;Lredis/clients/jedis/commands/ProtocolCommand;[[B)V:normal
  sendCommand(Lredis/clients/jedis/util/RedisOutputStream;[B[[B)V:normal

lazyclass:redis/clients/jedis/util/RedisInputStream
  ensureFill()V:normal
  read([BII)I:normal
  readByte()B:normal

lazyclass:redis/clients/jedis/util/RedisOutputStream
  flush()V:normal
  flushBuffer()V:normal
  write([B)V:normal
  write([BII)V:normal

lazyclass:redis/clients/jedis/Connection
#mark from sub redis/clients/jedis/BinaryClient
  connect()V:just_mark

lazyclass:redis/clients/jedis/commands/Commands
#mark from sub redis/clients/jedis/Client
  set(Ljava/lang/String;Ljava/lang/String;)V:just_mark

lazyclass:redis/clients/jedis/commands/JedisCommands
#mark from sub redis/clients/jedis/Jedis
  get(Ljava/lang/String;)Ljava/lang/String;:just_mark
#mark from sub redis/clients/jedis/Jedis
  set(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;:just_mark



```

So we close it now.

**Comment by xfeep** [comment]
@OneHappyStone Commit bf5d88e also includes a redis client test for coroutine mode.
