### ISSUE TITLE
JDK v11 java.lang.ClassCastException error

### ISSUE THREAD

**Issue by perisicboro** [nginx-clojure/nginx-clojure#221]
I am getting this error with JDK version 11.

`2019-09-27 16:58:39[info][3508][main][nginx-clojure embed] server started!
2019-09-27 16:58:39[info][3508][main][nginx-clojure embed] server listening at port 8080.
Exception in thread "nginx-clojure-embed" java.lang.ClassCastException: class [B cannot be cast to class [C ([B and [C are in module java.base of loader 'bootstrap')
    at nginx.clojure.HackUtils.encode(HackUtils.java:226)
    at nginx.clojure.UnknownHeaderHolder.fetch(UnknownHeaderHolder.java:114)
    at nginx.clojure.clj.LazyRequestMap$1.fetch(LazyRequestMap.java:86)
    at nginx.clojure.clj.LazyRequestMap.element(LazyRequestMap.java:308)
    at nginx.clojure.clj.LazyRequestMap.valAt(LazyRequestMap.java:323)
    at nginx.clojure.clj.LazyRequestMap.isWebSocket(LazyRequestMap.java:425)
    at nginx.clojure.NginxSimpleHandler.execute(NginxSimpleHandler.java:94)
    at nginx.clojure.NginxClojureRT.eval(NginxClojureRT.java:1133)
    at nginx.clojure.embed.NginxEmbedServer.innerStart(Native Method)
    at nginx.clojure.embed.NginxEmbedServer.access$000(NginxEmbedServer.java:31)
    at nginx.clojure.embed.NginxEmbedServer$1.run(NginxEmbedServer.java:323)
    at java.base/java.lang.Thread.run(Thread.java:834)
Connecting to local nREPL server...
`

**Comment by micahasmith** [comment]
same issue here.

**Comment by xfeep** [comment]
0.5.0 will support Java 11 and it will be released this week end.

**Comment by xfeep** [comment]
0.5.0 has been released!
