### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: can not load factory:nginx.clojure.groovy.NginxGroovyHandlerFactory

### ISSUE THREAD

**Issue by hebbaa** [nginx-clojure/nginx-clojure#240]
I am getting below exception

Exception in thread "main" java.lang.RuntimeException: can not load factory:nginx.clojure.groovy.NginxGroovyHandlerFactory
	at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:36)
	at nginx.clojure.NginxHandlerFactory.fetchHandler(NginxHandlerFactory.java:43)
	at nginx.clojure.NginxClojureRT.registerCode(NginxClojureRT.java:861)
Caused by: java.lang.ClassNotFoundException: groovy.lang.GroovyClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at nginx.clojure.groovy.NginxGroovyHandlerFactory.<init>(NginxGroovyHandlerFactory.java:24)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at nginx.clojure.NginxHandlerFactory.fetchFactory(NginxHandlerFactory.java:33)
	... 2 more
2020/09/29 09:19:59 [error] 23098#0: invalid groovy content_handler code :  
               import nginx.clojure.java.NginxJavaRingHandler;
               import java.util.Map;
               public class HelloGroovy implements NginxJavaRingHandler {
                  public Object[] invoke(Map<String, Object> request){
                     return [200, //http status 200
                             ["Content-Type":"text/html"], //headers map
                             "Hello, Groovy & Nginx!"]; //response body can be string, File or Array/Collection of them
                  }
               }
          

I know it's a class path issue.  But i have set  class path as mentioned in the doc.

Here is my class path setting  in nginx.conf

 jvm_classpath  "libs/res/*"

libs/res contains all required jars

-rwxrwxrwx@ 1  957540 Sep 29 01:08 nginx-clojure-0.5.1.jar
-rwxrwxrwx@ 1   4991077 Sep 29 01:08 nginx-clojure-embed-0.5.1.jar
-rwxrwxrwx@ 1    12507 Sep 29 01:08 nginx-jersey-0.1.6.jar
-rwxrwxrwx@ 1  46392 Sep 29 01:08 nginx-tomcat8-0.2.6.jar

Any help is appreciated

**Comment by hebbaa** [comment]
I was able to  resolve the issue.
clojure-1.5.1.jar. was not there in the class path.

One suggestion:
===============
It will be convenient if all the required jars are part of  libs/res folder when the nginx  clojure is donloaded.
The reason being default nginx.conf refers  to  libs/* as class path and by default this directory is empty which causes confusion and error.

**Comment by hebbaa** [comment]
I was able to resolve the issue.
clojure-1.5.1.jar. was not there in the class path.

One suggestion:
It will be convenient if all the required jars are part of libs/res folder when the nginx clojure is donloaded.
The reason being default nginx.conf refers to libs/* as class path and by default this directory is empty which causes confusion and error.
