### ISSUE TITLE
aarch64 support on OSX

### ISSUE THREAD

**Issue by lbourdages** [nginx-clojure/nginx-clojure#276]
Starting an embedded server does not work on M1/M2 Macs, failing with the following exception:
```

Caused by: java.lang.RuntimeException: can not get slib/nginx-clojure-embed-macosx-aarch64.dylib at class path
	at nginx.clojure.embed.NginxEmbedServer.loadDynamicLibrary(NginxEmbedServer.java:74)
	at nginx.clojure.embed.NginxEmbedServer.<clinit>(NginxEmbedServer.java:45)
	... 32 more

```

Are there any plans to support aarch64 for Mac in the future?

**Comment by xfeep** [comment]
Sorry so far we have no aarch64 DEV environment.
