### ISSUE TITLE
java.lang.VerifyError happens when use mysql jdbc 8.0.32 on jdk19 + nginx-clojure 0.6.0 

### ISSUE THREAD

**Issue by xfeep** [nginx-clojure/nginx-clojure#279]
When use mysql jdbc 8.0.32 on jdk19 + nginx-clojure 0.6.0 with native coroutine enabled,  java.lang.VerifyError happens.

```java
Exception in thread "nginx-clojure-embed" java.lang.VerifyError: Expecting a stackmap frame at branch target 12
Exception Details:
  Location:
    com/mysql/cj/jdbc/NonRegisteringDriver.<clinit>()V @0: ldc
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0000000: 123a b600 3bb8 003c 57a7 0004 4bb1     
  Exception Handler Table:
    bci [0, 9] => handler: 12

	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:390)
	at java.base/java.lang.Class.forName(Class.java:381)

```

**Comment by xfeep** [comment]
```
jvm_options "-Xverify:none";
```
This option can be used to work around this issue.
