### ISSUE TITLE
Unable to add headers when proxy pass

### ISSUE THREAD

**Issue by kalyanjennu** [nginx-clojure/nginx-clojure#65]
Hi,

 I am using nginx clojure for a proxy pass. In my java library if i try to add headers to the request to pass to the backend, i get the below exception.
java.lang.UnsupportedOperationException: put request header  not supported now!
	at nginx.clojure.java.JavaLazyHeaderMap.put(JavaLazyHeaderMap.java:238)
	at com.nap.nginx.NginxRequestHandler.invoke(NginxRequestHandler.java:59)
	at nginx.clojure.java.NginxJavaHandler.process(NginxJavaHandler.java:74)
	at nginx.clojure.NginxSimpleHandler.handleRequest(NginxSimpleHandler.java:120)
	at nginx.clojure.NginxSimpleHandler$1.call(NginxSimpleHandler.java:96)

**Comment by kalyanjennu** [comment]
I found the answer on google groups.
